### ISSUE TITLE
browser / live page?

### ISSUE THREAD

**Issue by jbenet** [ipfs-shipyard/p2p-flipchart#4]
does it work in the browse? is there a live page with this? would like to check it out w/o building locally.

**Comment by jbenet** [comment]
(i understand it's meant to be DIY and for people to work with)

**Comment by daviddias** [comment]
@pgte wanna publish it under flipchart.peerpad.net?

**Comment by pgte** [comment]
I was going to publish it as a github page, but that also sounds good, although we’ll need a certificate..

**Comment by daviddias** [comment]
@lgierth mind handling the certificate request?

**Comment by ghost** [comment]
Sure, for which domain?

**Comment by ghost** [comment]
Ah I see, flipchart.peerpad.net

**Comment by ghost** [comment]
It's up: https://flipchart.peerpad.net/

@pgte you can edit it with the same DNSimple account.

**Comment by pgte** [comment]
thanks @lgierth !

**Comment by daviddias** [comment]
@pgte anything blocking you from publishing this?

**Comment by pgte** [comment]
@diasdavid other than time and other priorities (PeerPad), nothing :)
Will start on this after #5.

**Comment by daviddias** [comment]
After publish, also add a link to it from PeerPad :)

**Comment by pgte** [comment]
It's live! https://flipchart.peerpad.net
