### ISSUE TITLE
Update to latest ipfs

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/p2p-flipchart#5]
Same as https://github.com/ipfs-shipyard/peerpad/issues/125

**Comment by pgte** [comment]
IPFS version 0.27.0 doesn't work.
My local copy that has IPFS master and some dependencies linked fixes it.
Should be the same issue as this peerpad one: https://github.com/ipfs-shipyard/peerpad/issues/125

I guess this needs a new IPFS patch release.

**Comment by daviddias** [comment]
@pgte see my comment https://github.com/ipfs-shipyard/peerpad/issues/125#issuecomment-349740524
